stock:
    resource: "@StockBundle/Controller/"
    type:     annotation
    prefix:   /

client:
    resource: "@ClientBundle/Controller/"
    type:     annotation
    prefix:   /

front:
    resource: "@FrontBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
