<?php

namespace ClientBundle\Repository;

/**
 * TypeSoinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeSoinRepository extends \Doctrine\ORM\EntityRepository
{
}
