<?php

namespace FrontBundle\Repository;

/**
 * CoiffeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoiffeurRepository extends \Doctrine\ORM\EntityRepository
{
}
